spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.134.193.80:3306/website?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 不告诉你
  data:
    redis:
      host: 8.134.193.80
      port: 6379
      connect-timeout: 5000
      password: 不告诉你
  servlet:
    multipart:
      max-file-size: 100MB


mybatis:
  type-aliases-package: siwenyu.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
debug: true

